# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-01 18:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0004_auto_20160701_1711'),
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='University Name')),
            ],
        ),
        migrations.AddField(
            model_name='author',
            name='university',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bookstore.University'),
            preserve_default=False,
        ),
    ]
