# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-01 19:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0005_auto_20160701_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='university',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='bookstore.University'),
        ),
    ]
